project_id = "qknytkvatzsmesmvyalv"

[functions.submit-quote]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.submit-brief]
verify_jwt = false

[functions.sync-hubspot-contact]
verify_jwt = false
