-- Add remaining industry pages
INSERT INTO content_pages (slug, title, content, status, page_type, created_by, updated_by)
VALUES 
  ('industries/events', 'Out-of-Home Advertising for Events & Entertainment', '{"hero_title": "Out-of-Home Advertising for Events & Entertainment", "hero_description": "Drive event attendance with strategic outdoor advertising campaigns."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/fashion', 'Out-of-Home Advertising for Fashion & Lifestyle', '{"hero_title": "Out-of-Home Advertising for Fashion & Lifestyle", "hero_description": "Premium outdoor advertising solutions for fashion and lifestyle brands."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/financial-services', 'Out-of-Home Advertising for Financial Services', '{"hero_title": "Out-of-Home Advertising for Financial Services", "hero_description": "Trusted outdoor advertising for financial services and fintech companies."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/food', 'Out-of-Home Advertising for Food & Drink', '{"hero_title": "Out-of-Home Advertising for Food & Drink", "hero_description": "Appetite-driving outdoor advertising for food and beverage brands."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/government', 'Out-of-Home Advertising for Government & Public Sector', '{"hero_title": "Out-of-Home Advertising for Government & Public Sector", "hero_description": "Public awareness campaigns through strategic outdoor advertising."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/healthcare', 'Out-of-Home Advertising for Healthcare Industry', '{"hero_title": "Out-of-Home Advertising for Healthcare Industry", "hero_description": "Compliant outdoor advertising solutions for healthcare providers."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/property', 'Out-of-Home Advertising for Property & Real Estate', '{"hero_title": "Out-of-Home Advertising for Property & Real Estate", "hero_description": "Drive property inquiries with targeted outdoor advertising campaigns."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/recruitment', 'Out-of-Home Advertising for Recruitment Industry', '{"hero_title": "Out-of-Home Advertising for Recruitment Industry", "hero_description": "Attract top talent through strategic outdoor advertising campaigns."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/retail', 'Out-of-Home Advertising for Retail Industry', '{"hero_title": "Out-of-Home Advertising for Retail Industry", "hero_description": "Drive footfall and sales with strategic retail outdoor advertising."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/startups', 'Out-of-Home Advertising for Startups & Scaleups', '{"hero_title": "Out-of-Home Advertising for Startups & Scaleups", "hero_description": "Cost-effective outdoor advertising solutions for growing businesses."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/technology', 'Out-of-Home Advertising for Technology Sector', '{"hero_title": "Out-of-Home Advertising for Technology Sector", "hero_description": "Innovative outdoor advertising for tech companies and SaaS businesses."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/travel', 'Out-of-Home Advertising for Travel & Hospitality', '{"hero_title": "Out-of-Home Advertising for Travel & Hospitality", "hero_description": "Inspire wanderlust with captivating outdoor advertising campaigns."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1))
ON CONFLICT (slug) DO NOTHING;