-- Add industry pages (first batch)
INSERT INTO content_pages (slug, title, content, status, page_type, created_by, updated_by)
VALUES 
  ('industries/automotive', 'Out-of-Home Advertising for Automotive Industry', '{"hero_title": "Out-of-Home Advertising for Automotive Industry", "hero_description": "Strategic outdoor advertising campaigns for automotive brands across London."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/agencies', 'Out-of-Home Advertising for Agencies & In-House Teams', '{"hero_title": "Out-of-Home Advertising for Agencies & In-House Teams", "hero_description": "Professional OOH media buying services for agencies and in-house marketing teams."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/beauty', 'Out-of-Home Advertising for Beauty & Wellness', '{"hero_title": "Out-of-Home Advertising for Beauty & Wellness", "hero_description": "Outdoor advertising solutions for beauty and wellness brands in London."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/construction', 'Out-of-Home Advertising for Construction & Trade', '{"hero_title": "Out-of-Home Advertising for Construction & Trade", "hero_description": "Effective outdoor advertising for construction and trade businesses."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/education', 'Out-of-Home Advertising for Education Sector', '{"hero_title": "Out-of-Home Advertising for Education Sector", "hero_description": "Strategic outdoor advertising campaigns for educational institutions."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1)),
  ('industries/entertainment', 'Out-of-Home Advertising for Entertainment Industry', '{"hero_title": "Out-of-Home Advertising for Entertainment Industry", "hero_description": "High-impact outdoor advertising for entertainment and media brands."}', 'published', 'industry', (SELECT id FROM auth.users LIMIT 1), (SELECT id FROM auth.users LIMIT 1))
ON CONFLICT (slug) DO NOTHING;