-- Insert industry pages into content_pages
INSERT INTO public.content_pages (id, page_type, title, slug, content, created_by, updated_by, created_at, updated_at) VALUES
(gen_random_uuid(), 'industry', 'Out-of-Home Advertising for Automotive Industry', 'automotive', '{"sections":[{"type":"hero","title":"Drive Your Automotive Brand Forward","subtitle":"Capture the attention of drivers and passengers with strategic out-of-home advertising that reaches your audience where they spend their time - on the road.","image":"/placeholder.svg"},{"type":"features","title":"Why OOH Works for Automotive","items":[{"title":"High-Impact Visibility","description":"Billboard and roadside advertising creates maximum exposure for vehicle launches and promotions"},{"title":"Location Targeting","description":"Reach potential customers near dealerships, service centers, and high-traffic automotive areas"},{"title":"Brand Awareness","description":"Build consistent brand recognition through repeated exposure during daily commutes"}]},{"type":"cta","title":"Ready to Drive Results?","subtitle":"Let us help you create an automotive advertising campaign that gets your brand noticed on every journey.","buttonText":"Get Your Quote","buttonLink":"/quote"}]}', NULL, NULL, now(), now()),

(gen_random_uuid(), 'industry', 'Out-of-Home Advertising for Retail Industry', 'retail', '{"sections":[{"type":"hero","title":"Boost Your Retail Sales with OOH","subtitle":"Drive foot traffic to your stores with strategic outdoor advertising that captures shoppers at the perfect moment.","image":"/placeholder.svg"},{"type":"features","title":"Retail Advertising Solutions","items":[{"title":"Shopping Center Displays","description":"Target customers directly at malls and retail parks with high-impact displays"},{"title":"Transit Advertising","description":"Reach commuters and shoppers on buses, trains, and stations"},{"title":"Street Furniture","description":"Utilize bus stops, phone kiosks, and digital screens in high-footfall areas"}]},{"type":"cta","title":"Increase Store Visits Today","subtitle":"Transform passersby into customers with compelling retail advertising campaigns.","buttonText":"Start Your Campaign","buttonLink":"/quote"}]}', NULL, NULL, now(), now()),

(gen_random_uuid(), 'industry', 'Out-of-Home Advertising for Technology Sector', 'technology', '{"sections":[{"type":"hero","title":"Amplify Your Tech Brand Presence","subtitle":"Make your technology solutions impossible to ignore with strategic outdoor advertising that reaches decision-makers everywhere.","image":"/placeholder.svg"},{"type":"features","title":"Tech Industry Advertising","items":[{"title":"B2B Targeting","description":"Reach business districts and corporate areas where your target audience works"},{"title":"Innovation Showcase","description":"Demonstrate cutting-edge products through dynamic digital displays"},{"title":"Event Amplification","description":"Maximize conference and launch event impact with surrounding area advertising"}]},{"type":"cta","title":"Scale Your Tech Marketing","subtitle":"Connect with innovators and early adopters through strategic out-of-home advertising.","buttonText":"Explore Solutions","buttonLink":"/quote"}]}', NULL, NULL, now(), now()),

(gen_random_uuid(), 'industry', 'Out-of-Home Advertising for Healthcare Industry', 'healthcare', '{"sections":[{"type":"hero","title":"Promote Health & Wellness Effectively","subtitle":"Build trust and awareness for your healthcare services with thoughtful, community-focused outdoor advertising.","image":"/placeholder.svg"},{"type":"features","title":"Healthcare Marketing Solutions","items":[{"title":"Community Outreach","description":"Connect with local communities through neighborhood and transit advertising"},{"title":"Trust Building","description":"Establish credibility with professional, informative campaign messaging"},{"title":"Service Awareness","description":"Promote new services, facilities, and health initiatives effectively"}]},{"type":"cta","title":"Improve Community Health Awareness","subtitle":"Reach patients and families with healthcare advertising that makes a difference.","buttonText":"Get Started","buttonLink":"/quote"}]}', NULL, NULL, now(), now()),

(gen_random_uuid(), 'industry', 'Out-of-Home Advertising for Financial Services', 'financial-services', '{"sections":[{"type":"hero","title":"Build Financial Trust Through OOH","subtitle":"Establish credibility and reach potential clients with professional outdoor advertising for banking, insurance, and financial services.","image":"/placeholder.svg"},{"type":"features","title":"Financial Services Advertising","items":[{"title":"Professional Presence","description":"Build brand authority with premium outdoor advertising locations"},{"title":"Local Market Penetration","description":"Target specific communities and business districts effectively"},{"title":"Trust & Credibility","description":"Reinforce stability and reliability through consistent brand presence"}]},{"type":"cta","title":"Grow Your Financial Business","subtitle":"Attract new clients and build lasting relationships through strategic outdoor advertising.","buttonText":"Learn More","buttonLink":"/quote"}]}', NULL, NULL, now(), now()),

(gen_random_uuid(), 'industry', 'Out-of-Home Advertising for Entertainment Industry', 'entertainment', '{"sections":[{"type":"hero","title":"Create Buzz for Entertainment Brands","subtitle":"Generate excitement and anticipation for movies, shows, events, and entertainment venues with high-impact outdoor advertising.","image":"/placeholder.svg"},{"type":"features","title":"Entertainment Advertising Power","items":[{"title":"Event Promotion","description":"Drive ticket sales and attendance with strategically placed campaign materials"},{"title":"Venue Branding","description":"Establish entertainment destinations as must-visit locations"},{"title":"Audience Excitement","description":"Create anticipation and buzz through dynamic, eye-catching displays"}]},{"type":"cta","title":"Make Your Event Unmissable","subtitle":"Turn every passerby into a potential audience member with compelling entertainment advertising.","buttonText":"Plan Your Campaign","buttonLink":"/quote"}]}', NULL, NULL, now(), now()),

(gen_random_uuid(), 'industry', 'Out-of-Home Advertising for Education Sector', 'education', '{"sections":[{"type":"hero","title":"Reach Students & Parents Effectively","subtitle":"Promote educational institutions, programs, and services with targeted outdoor advertising that connects with learning communities.","image":"/placeholder.svg"},{"type":"features","title":"Education Marketing Solutions","items":[{"title":"Student Recruitment","description":"Attract prospective students with campus-area and transit advertising"},{"title":"Program Awareness","description":"Promote new courses, degrees, and educational opportunities"},{"title":"Community Engagement","description":"Build relationships with local families and educational stakeholders"}]},{"type":"cta","title":"Enroll More Students Today","subtitle":"Make your educational institution the top choice with strategic outdoor advertising.","buttonText":"Start Recruiting","buttonLink":"/quote"}]}', NULL, NULL, now(), now()),

(gen_random_uuid(), 'industry', 'Out-of-Home Advertising for Real Estate', 'real-estate', '{"sections":[{"type":"hero","title":"Sell Properties Faster with OOH","subtitle":"Showcase properties and real estate services with location-based outdoor advertising that reaches buyers and sellers where it matters most.","image":"/placeholder.svg"},{"type":"features","title":"Real Estate Advertising Strategy","items":[{"title":"Property Showcasing","description":"Feature listings and developments with high-quality outdoor displays"},{"title":"Local Market Presence","description":"Establish authority in specific neighborhoods and property markets"},{"title":"Agent Branding","description":"Build recognition for real estate professionals and agencies"}]},{"type":"cta","title":"Close More Deals","subtitle":"Connect with property buyers and sellers through strategic real estate advertising.","buttonText":"View Options","buttonLink":"/quote"}]}', NULL, NULL, now(), now());

-- Insert corresponding SEO data for industry pages
INSERT INTO public.seo_pages (id, page_path, title, description, keywords, og_title, og_description, og_image, twitter_title, twitter_description, twitter_image, canonical_url, schema_markup, created_at, updated_at) VALUES
(gen_random_uuid(), '/industries/automotive', 'Automotive Out-of-Home Advertising | Drive Brand Awareness', 'Boost your automotive brand with strategic OOH advertising. Reach drivers and potential customers with billboard, roadside, and transit advertising solutions.', 'automotive advertising, car advertising, vehicle marketing, automotive OOH, billboard advertising automotive', 'Automotive Out-of-Home Advertising Solutions', 'Drive your automotive brand forward with strategic out-of-home advertising that reaches customers on the road.', '/placeholder.svg', 'Automotive OOH Advertising', 'Strategic outdoor advertising for automotive brands and dealerships.', '/placeholder.svg', 'https://mediabuyinglondon.com/industries/automotive', '{"@context":"https://schema.org","@type":"Service","name":"Automotive Out-of-Home Advertising","description":"Strategic outdoor advertising solutions for automotive brands, dealerships, and car manufacturers.","provider":{"@type":"Organization","name":"Media Buying London"}}', now(), now()),

(gen_random_uuid(), '/industries/retail', 'Retail Out-of-Home Advertising | Increase Store Traffic', 'Drive foot traffic to your retail stores with strategic OOH advertising. Shopping center displays, transit ads, and street furniture solutions for retailers.', 'retail advertising, store advertising, shopping center advertising, retail OOH, foot traffic advertising', 'Retail Out-of-Home Advertising Solutions', 'Boost retail sales and drive store visits with strategic outdoor advertising targeting shoppers.', '/placeholder.svg', 'Retail OOH Advertising', 'Drive foot traffic and sales with targeted retail outdoor advertising.', '/placeholder.svg', 'https://mediabuyinglondon.com/industries/retail', '{"@context":"https://schema.org","@type":"Service","name":"Retail Out-of-Home Advertising","description":"Outdoor advertising solutions designed to drive foot traffic and sales for retail businesses.","provider":{"@type":"Organization","name":"Media Buying London"}}', now(), now()),

(gen_random_uuid(), '/industries/technology', 'Technology Out-of-Home Advertising | Tech Brand Amplification', 'Amplify your technology brand with strategic OOH advertising. Reach decision-makers and innovators with B2B outdoor advertising solutions.', 'technology advertising, tech advertising, B2B outdoor advertising, tech OOH, innovation marketing', 'Technology Out-of-Home Advertising Solutions', 'Make your tech solutions impossible to ignore with strategic outdoor advertising for technology companies.', '/placeholder.svg', 'Tech OOH Advertising', 'Strategic outdoor advertising for technology companies and B2B solutions.', '/placeholder.svg', 'https://mediabuyinglondon.com/industries/technology', '{"@context":"https://schema.org","@type":"Service","name":"Technology Out-of-Home Advertising","description":"Strategic outdoor advertising solutions for technology companies and B2B tech services.","provider":{"@type":"Organization","name":"Media Buying London"}}', now(), now()),

(gen_random_uuid(), '/industries/healthcare', 'Healthcare Out-of-Home Advertising | Medical Marketing', 'Promote healthcare services with trusted OOH advertising. Community-focused outdoor advertising solutions for hospitals, clinics, and medical services.', 'healthcare advertising, medical advertising, hospital advertising, healthcare OOH, medical marketing', 'Healthcare Out-of-Home Advertising Solutions', 'Build trust and awareness for healthcare services with community-focused outdoor advertising.', '/placeholder.svg', 'Healthcare OOH Advertising', 'Trusted outdoor advertising solutions for healthcare providers and medical services.', '/placeholder.svg', 'https://mediabuyinglondon.com/industries/healthcare', '{"@context":"https://schema.org","@type":"Service","name":"Healthcare Out-of-Home Advertising","description":"Community-focused outdoor advertising solutions for healthcare providers and medical services.","provider":{"@type":"Organization","name":"Media Buying London"}}', now(), now()),

(gen_random_uuid(), '/industries/financial-services', 'Financial Services OOH Advertising | Banking Marketing', 'Build financial trust with professional OOH advertising. Premium outdoor advertising solutions for banks, insurance, and financial services.', 'financial advertising, banking advertising, insurance advertising, financial OOH, financial services marketing', 'Financial Services Out-of-Home Advertising', 'Establish credibility and reach clients with professional outdoor advertising for financial services.', '/placeholder.svg', 'Financial Services OOH', 'Professional outdoor advertising for banking, insurance, and financial services.', '/placeholder.svg', 'https://mediabuyinglondon.com/industries/financial-services', '{"@context":"https://schema.org","@type":"Service","name":"Financial Services Out-of-Home Advertising","description":"Professional outdoor advertising solutions for banks, insurance companies, and financial service providers.","provider":{"@type":"Organization","name":"Media Buying London"}}', now(), now()),

(gen_random_uuid(), '/industries/entertainment', 'Entertainment Out-of-Home Advertising | Event Promotion', 'Create buzz for entertainment with dynamic OOH advertising. Event promotion, venue branding, and audience engagement through outdoor advertising.', 'entertainment advertising, event advertising, venue advertising, entertainment OOH, event promotion', 'Entertainment Out-of-Home Advertising Solutions', 'Generate excitement for entertainment brands with high-impact outdoor advertising campaigns.', '/placeholder.svg', 'Entertainment OOH Advertising', 'Dynamic outdoor advertising for entertainment venues, events, and media promotion.', '/placeholder.svg', 'https://mediabuyinglondon.com/industries/entertainment', '{"@context":"https://schema.org","@type":"Service","name":"Entertainment Out-of-Home Advertising","description":"Dynamic outdoor advertising solutions for entertainment venues, events, and media promotion.","provider":{"@type":"Organization","name":"Media Buying London"}}', now(), now()),

(gen_random_uuid(), '/industries/education', 'Education Out-of-Home Advertising | Student Recruitment', 'Reach students and parents with targeted OOH advertising. Educational institution marketing and student recruitment through outdoor advertising.', 'education advertising, student recruitment, university advertising, education OOH, school marketing', 'Education Out-of-Home Advertising Solutions', 'Promote educational institutions and recruit students with targeted outdoor advertising campaigns.', '/placeholder.svg', 'Education OOH Advertising', 'Strategic outdoor advertising for educational institutions and student recruitment.', '/placeholder.svg', 'https://mediabuyinglondon.com/industries/education', '{"@context":"https://schema.org","@type":"Service","name":"Education Out-of-Home Advertising","description":"Targeted outdoor advertising solutions for educational institutions and student recruitment.","provider":{"@type":"Organization","name":"Media Buying London"}}', now(), now()),

(gen_random_uuid(), '/industries/real-estate', 'Real Estate Out-of-Home Advertising | Property Marketing', 'Sell properties faster with strategic OOH advertising. Real estate marketing solutions for agents, developers, and property companies.', 'real estate advertising, property advertising, real estate OOH, property marketing, real estate agents', 'Real Estate Out-of-Home Advertising Solutions', 'Showcase properties and real estate services with location-based outdoor advertising.', '/placeholder.svg', 'Real Estate OOH Advertising', 'Strategic outdoor advertising for real estate agents, developers, and property companies.', '/placeholder.svg', 'https://mediabuyinglondon.com/industries/real-estate', '{"@context":"https://schema.org","@type":"Service","name":"Real Estate Out-of-Home Advertising","description":"Location-based outdoor advertising solutions for real estate agents, developers, and property companies.","provider":{"@type":"Organization","name":"Media Buying London"}}', now(), now());