// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qknytkvatzsmesmvyalv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbnl0a3ZhdHpzbWVzbXZ5YWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTY0MjcsImV4cCI6MjA2OTk5MjQyN30.bpEM3jVhIymmO05GR4s8FTkXQ6uZc3ksP7uNtBDb3fQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});